name: Docker Image

on:
  push:
  workflow_dispatch:

jobs:
  docker:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-docker]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Container Registry
        uses: docker/login-action@v1.14.1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/atestacraft/chatemotes-api:latest
            ghcr.io/atestacraft/chatemotes-api:${{ github.sha }}